function Mod:init()
    Game.usingninjabelt = false
    Game:registerEvent("squeak", function(data)
        return Squeak(data.x, data.y, {data.width, data.height, data.polygon})
    end)
    Game:registerEvent("greedpurg_base", function(data)
        return greedpurg_base(data.x, data.y, {data.width, data.height, data.polygon})
    end)
    Game:registerEvent("greedpurg_gift", function(data)
        return greedpurg_gift(data.x, data.y, {data.width, data.height, data.polygon})
    end)
    Game:registerEvent("pylon", function(data)
        return pylon(data.x, data.y, {data.width, data.height, data.polygon})
    end)
    love.window.setTitle("Nullrune")
    love.window.setIcon(Assets.getTextureData("window_icon"))
    print("Loaded " .. self.info.name .. "!")
end
